theme: jekyll

##teamtime pages

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: teamtimepost
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : THU HPC
email      : chenjc20@mails.tsinghua.edu.cn #this is also the email contact forms will go to
description: ""
announce:  Last updated on March 10, 2021. Site made with [Jekyll.](https://jekyllrb.com/)
author     : Chen junchao
time       : 2021.03
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

collections:
  portfolio:

markdown: kramdown

